#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Darwin) brew install bitlbee ;;
    *)      pkg ensure chat/bitlbee ;;
  esac
}

main "$@"
