#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      brew install bitlbee
      ;;
    *)
      pkg ensure chat/bitlbee
      ;;
  esac
}

main "$@"
