#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_bitlbee="0.0.1"
  jq -n --arg bitlbee "$ver_bitlbee" '{bitlbee: $bitlbee}'
}

version "$@"
